name: 'nyc_analytics'          # dbt project name
version: '1.0.0'               # Project version
config-version: 2              # dbt project configuration format version

# Tells dbt which connection profile to use from profiles.yml
profile: 'default'

# File path settings
# These are standard dbt folders. If you use the default names,
# writing them here is optional, but it can improve readability.
model-paths:
  - models                    # Folder containing dbt models
analysis-paths:
  - analyses                  # Folder containing analysis SQL files
test-paths:
  - tests                     # Folder containing tests
seed-paths:
  - seeds                     # Folder containing CSV seed files
snapshot-paths:
  - snapshots                 # Folder containing snapshots

# Where dbt writes compiled SQL, logs, and artifacts
target-path: "target"

# Folders removed when `dbt clean` is run
clean-targets:
  - target
  - dbt_packages

# Model configuration
models:
  nyc_analytics: # Projet name -- same as above (line 1)
    +materialized: table      # Default: all models in this project build as tables

    assignment_work: # folder/path: model/assignment_work
      staging: # folder/path: model/assignment_work/staging
        +materialized: table  # Redundant: already inherited from nyc_analytics
        +schema: nyc_transit_restaurants_staging
        # Models in models/assignment_work/staging/ go to this schema

      marts: # folder/path: model/mart
        +materialized: table    # Redundant: already inherited from nyc_analytics
        +schema: nyc_transit_restaurants_marts
        # Models in models/marts/ go to this schema

        shared: # folder/path: model/mart/shared
          +materialized: table  # Redundant: inherited from marts and nyc_analytics

        open_restaurant_apps: # folder/path: model/open_restaurant_apps
          +materialized: table    # Redundant: already inherited from nyc_analytics

        dot_311: # folder/path: model/dot_311
          +materialized: table    # Redundant: already inherited from nyc_analytics